// ---------------------------------------------------------------------------
// keyboard_controller — PS/2 keyboard receiver (project addition).
//
// Hierarchy: FPGA80186 -> keyboard_controller  (reached via io_decode)
// Reference: DE1-SoC User Manual (PS/2 port)
// Testbench: sim/tb_keyboard.sv
//
// Not part of the 80186 itself -- the chip has no PS/2 or 8042-style keyboard
// controller, same as it has no VGA.
//
// PS/2 FRAME: the device drives 11 bits per byte -- a start bit (0), eight
// data bits LSB first, odd parity, and a stop bit (1) -- clocking each one out
// on its own falling edge. The host samples on that falling edge. ps2_clk is
// asynchronous to everything here (it is generated by the keyboard), so it is
// synchronised before any edge detection.
//
// RESYNC: if a frame stalls part-way through, the shift state is reset after
// an idle timeout. Without that, one glitch desynchronises the receiver
// permanently and every subsequent key is garbage -- a failure mode that looks
// like a dead keyboard rather than a lost bit.
//
// BUFFERING: an 8-byte FIFO, because a single holding register drops keys
// whenever the CPU is slow to read, and a dropped key is far more annoying to
// diagnose than the handful of registers this costs.
//
// REGISTER INTERFACE, modelled loosely on the PC's 8042 ports:
//   port 0 (60h)  data   -- reading pops the FIFO
//   port 1 (64h)  status -- bit 0 set when a byte is waiting
//
// SCANCODE TRANSLATION (XLAT), and why it has to be HERE rather than in the
// BIOS. PS/2 keyboards send set 2; PC software expects set 1 (XT), and on a
// real PC the 8042 translates between them. This was left undone for a long
// time with the note that translating here or in the BIOS was an open
// decision. It is not: DOOM8088 -- and every other game that wants to know
// which keys are held down -- installs its OWN int 09h and reads port 60h
// directly, so the BIOS translation never runs for exactly the software that
// matters most. Translating in the BIOS would have fixed typing and nothing
// else.
//
// The symptom before this existed was not "no keyboard"; it was keys that
// stuck down. Set 2 marks a release as F0 <code>, while set 1 marks it by
// setting bit 7. Software testing `code & 0x80` sees the F0 PREFIX itself as
// a key-up, then reads the real scancode that follows as a fresh key-DOWN --
// so letting go of a key registers as pressing it again.
//
// The table is the 8042's own, and the SAME table applies to the byte after
// an E0 -- which is why extended keys need no second table. A code with no
// set 1 equivalent maps to 00 and is dropped rather than passed on as noise.
//
// NOT IMPLEMENTED
//   - The Pause/Break key, which sends an E1-prefixed eight-byte sequence.
//     E1 is not recognised, so its bytes are translated as if they were
//     ordinary keys. Nothing uses Pause.
//   - Host-to-device transmit (see below), so the keyboard is never asked to
//     switch sets; it is left in its power-on default of set 2 and translated
//     here, exactly as a PC does.
//   - Host-to-device transmit. That needs ps2_clk/ps2_dat as bidirectional
//     open-drain, since the host signals by pulling clock low. Only required
//     for setting LEDs or driving a mouse.
// ---------------------------------------------------------------------------

`timescale 1ns/1ns
module keyboard_controller #(
    // Idle cycles before a partial frame is abandoned. A PS/2 clock is
    // 10-16 kHz, so at any sane CPU clock this is far longer than one bit
    // period and far shorter than a human keypress.
    parameter int IDLE_LIMIT = 20000,
    // Translate set 2 to set 1 on the way into the FIFO. Clearing it hands
    // software the raw bytes off the wire, which is what this did before and
    // is occasionally useful when debugging the PS/2 link itself -- but the
    // BIOS's own key table is set 1 now, so a build with this clear will not
    // type correctly either.
    parameter bit XLAT = 1'b1
) (
    input  logic       clk,
    input  logic       rst_n,

    // PS/2 port (DE1-SoC board pins)
    input  logic       ps2_clk,
    input  logic       ps2_dat,

    // CPU-facing register interface (address decode done by io_decode).
    //
    // CONTRACT: `rd` and `wr` are SINGLE-CYCLE strobes marking a completed
    // access, not the raw bus RD/WR -- io_decode narrows them. Reading the
    // data port pops the FIFO, so a multi-cycle level here would retire two
    // or more entries per access and hand the CPU the wrong byte. `sel` and
    // `port` are levels and stay valid for the whole cycle, which is what
    // `rdata` is driven from.
    input  logic       sel,
    input  logic       port,          // 0 = data, 1 = status
    input  logic       rd,
    input  logic       wr,
    input  logic [7:0] wdata,
    output logic [7:0] rdata,
    output logic       data_avail,

    // -> one of the interrupt controller's INT0-INT3 pins
    output logic       irq
);

    // ---- synchronise and find falling edges ----
    logic [2:0] clk_sync;
    logic       dat_sync;
    logic       falling;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            clk_sync <= 3'b111;
            dat_sync <= 1'b1;
        end else begin
            clk_sync <= {clk_sync[1:0], ps2_clk};
            dat_sync <= ps2_dat;
        end
    end
    assign falling = (clk_sync[2:1] == 2'b10);

    // ---- frame shift register ----
    logic [10:0] shreg;
    logic [3:0]  bitcnt;
    logic [$clog2(IDLE_LIMIT+1)-1:0] idle_cnt;

    logic        frame_done;
    logic [7:0]  frame_data;
    logic        frame_ok;

    assign frame_data = shreg[8:1];
    // Odd parity over the eight data bits plus the parity bit, a zero start
    // bit and a one stop bit.
    assign frame_ok   = (shreg[0] == 1'b0) && (shreg[10] == 1'b1) &&
                        (^shreg[9:1] == 1'b1);

    // ---- FIFO ----
    localparam int DEPTH = 8;
    // 8 x 8 bits = 64 bits. Left to itself Quartus infers an M10K for this and
    // then bolts pass-through logic onto it to reproduce the read-during-write
    // behaviour -- spending a whole 10 Kbit block, plus ALMs, to be slower
    // than the flops it replaced. Registers are the right home for a FIFO this
    // small, and the read port stays genuinely combinational.
    // ---- set 2 -> set 1, the 8042's table ----
    // Generated by tools/scancodes.py, which is also what gen_bios.py builds
    // the BIOS's key table from. Two hand-written copies of this would drift,
    // and the symptom would look like a broken keyboard rather than a
    // mismatch. sim/tb_keyboard.sv asserts the mappings DOOM8088 depends on.
    `include "scancodes.svh"

    logic       brk;                 // an F0 release prefix is pending
    logic [7:0] xt_code;
    logic       push;
    logic [7:0] push_data;

    assign xt_code = XT[frame_data];

    always_comb begin
        if (!XLAT) begin
            push      = frame_done && frame_ok;
            push_data = frame_data;
        end else if (!(frame_done && frame_ok)) begin
            push      = 1'b0;
            push_data = 8'h00;
        end else if (frame_data == 8'hE0) begin
            // Pass the prefix straight through: set 1 uses E0 too.
            push      = 1'b1;
            push_data = 8'hE0;
        end else if (frame_data == 8'hF0) begin
            // The release prefix has no set 1 equivalent -- it becomes bit 7
            // of the code that follows, so nothing is enqueued for it.
            push      = 1'b0;
            push_data = 8'h00;
        end else begin
            push      = (xt_code != 8'h00);
            push_data = {brk, xt_code[6:0]};
        end
    end

    (* ramstyle = "logic" *) logic [7:0] fifo [0:DEPTH-1];
    logic [2:0] head, tail;
    logic [3:0] count;

    logic pop;
    assign pop        = sel && rd && (port == 1'b0) && (count != 4'd0);
    assign data_avail = (count != 4'd0);

    // IRQ IS A LEVEL, NOT A PULSE. The interrupt controller samples its
    // external INT pins combinationally and latches nothing
    // (interrupt_controller.sv: request[S_INT0] = int0), so a one-clock pulse
    // is only seen if the CPU happens to be at an interruptible instruction
    // boundary that exact cycle. It usually is not, and the keystroke is lost
    // -- intermittently, which is the worst way for it to fail.
    //
    // Holding it asserted while a byte is pending is also what a real 8042
    // does, and it self-clears when software drains the FIFO. If more bytes
    // remain the request simply stays up and the handler is re-entered, which
    // is the behaviour a level-triggered input is supposed to have.
    assign irq = data_avail;
    assign rdata      = (port == 1'b0) ? fifo[head] : {7'h00, data_avail};

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            shreg      <= 11'h7FF;
            bitcnt     <= 4'd0;
            idle_cnt   <= '0;
            frame_done <= 1'b0;
            head       <= 3'd0;
            tail       <= 3'd0;
            count      <= 4'd0;
            brk        <= 1'b0;
        end else begin
            frame_done <= 1'b0;

            // ---- receive ----
            if (falling) begin
                idle_cnt <= '0;
                shreg    <= {dat_sync, shreg[10:1]};
                if (bitcnt == 4'd10) begin
                    bitcnt     <= 4'd0;
                    frame_done <= 1'b1;
                end else begin
                    bitcnt <= bitcnt + 4'd1;
                end
            end else if (bitcnt != 4'd0) begin
                // Only time out mid-frame; an idle line between keys is normal.
                if (idle_cnt == IDLE_LIMIT[$bits(idle_cnt)-1:0]) begin
                    bitcnt   <= 4'd0;
                    idle_cnt <= '0;
                end else begin
                    idle_cnt <= idle_cnt + 1'b1;
                end
            end

            // ---- break-code prefix ----
            // F0 arms it and any translated code consumes it. E0 clears it
            // too, which is worth spelling out because the obvious reading
            // says it should not: a released extended key is E0 F0 <code>,
            // so surely E0 must preserve a pending break? No -- the F0 comes
            // AFTER the E0 there and sets the flag itself, so E0 has nothing
            // to preserve. Clearing is then strictly better, because a frame
            // dropped on bad parity can leave the flag armed with no code to
            // consume it; the next E0 clears it instead of turning the
            // following keypress into a phantom release.
            if (frame_done && frame_ok) begin
                if (frame_data == 8'hF0) brk <= 1'b1;
                else                     brk <= 1'b0;
            end

            // ---- enqueue a good frame ----
            // A frame that fails parity or framing is dropped rather than
            // latched, so a corrupt byte never reaches software.
            if (push && (count < DEPTH)) begin
                fifo[tail] <= push_data;
                tail       <= tail + 3'd1;
                count      <= count + 4'd1 - {3'b0, pop};
            end else if (pop) begin
                count <= count - 4'd1;
            end

            if (pop) head <= head + 3'd1;
        end
    end

endmodule
