// ---------------------------------------------------------------------------
// keyboard_controller — PS/2 keyboard receiver (project addition).
//
// Hierarchy: FPGA80186 -> keyboard_controller  (reached via io_decode)
// Reference: DE1-SoC User Manual (PS/2 port)
// Testbench: sim/tb_keyboard.sv
//
// Not part of the 80186 itself -- the chip has no PS/2 or 8042-style keyboard
// controller, same as it has no VGA.
//
// PS/2 FRAME: the device drives 11 bits per byte -- a start bit (0), eight
// data bits LSB first, odd parity, and a stop bit (1) -- clocking each one out
// on its own falling edge. The host samples on that falling edge. ps2_clk is
// asynchronous to everything here (it is generated by the keyboard), so it is
// synchronised before any edge detection.
//
// RESYNC: if a frame stalls part-way through, the shift state is reset after
// an idle timeout. Without that, one glitch desynchronises the receiver
// permanently and every subsequent key is garbage -- a failure mode that looks
// like a dead keyboard rather than a lost bit.
//
// BUFFERING: an 8-byte FIFO, because a single holding register drops keys
// whenever the CPU is slow to read, and a dropped key is far more annoying to
// diagnose than the handful of registers this costs.
//
// REGISTER INTERFACE, modelled loosely on the PC's 8042 ports:
//   port 0 (60h)  data   -- reading pops the FIFO
//   port 1 (64h)  status -- bit 0 set when a byte is waiting
//
// NOT IMPLEMENTED
//   - Scancode set translation. PS/2 keyboards send set 2 by default while PC
//     BIOS/DOS software expects set 1 (XT) codes. Whether to translate here or
//     in the BIOS is a real decision, not an oversight; until it is made, raw
//     set 2 bytes come through and keys will produce the wrong characters for
//     PC-targeted software.
//   - Multi-byte sequences (E0 prefixes, F0 break codes) are passed through
//     as separate bytes rather than being combined.
//   - Host-to-device transmit. That needs ps2_clk/ps2_dat as bidirectional
//     open-drain, since the host signals by pulling clock low. Only required
//     for setting LEDs or driving a mouse.
// ---------------------------------------------------------------------------

`timescale 1ns/1ns
module keyboard_controller #(
    // Idle cycles before a partial frame is abandoned. A PS/2 clock is
    // 10-16 kHz, so at any sane CPU clock this is far longer than one bit
    // period and far shorter than a human keypress.
    parameter int IDLE_LIMIT = 20000
) (
    input  logic       clk,
    input  logic       rst_n,

    // PS/2 port (DE1-SoC board pins)
    input  logic       ps2_clk,
    input  logic       ps2_dat,

    // CPU-facing register interface (address decode done by io_decode).
    //
    // CONTRACT: `rd` and `wr` are SINGLE-CYCLE strobes marking a completed
    // access, not the raw bus RD/WR -- io_decode narrows them. Reading the
    // data port pops the FIFO, so a multi-cycle level here would retire two
    // or more entries per access and hand the CPU the wrong byte. `sel` and
    // `port` are levels and stay valid for the whole cycle, which is what
    // `rdata` is driven from.
    input  logic       sel,
    input  logic       port,          // 0 = data, 1 = status
    input  logic       rd,
    input  logic       wr,
    input  logic [7:0] wdata,
    output logic [7:0] rdata,
    output logic       data_avail,

    // -> one of the interrupt controller's INT0-INT3 pins
    output logic       irq
);

    // ---- synchronise and find falling edges ----
    logic [2:0] clk_sync;
    logic       dat_sync;
    logic       falling;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            clk_sync <= 3'b111;
            dat_sync <= 1'b1;
        end else begin
            clk_sync <= {clk_sync[1:0], ps2_clk};
            dat_sync <= ps2_dat;
        end
    end
    assign falling = (clk_sync[2:1] == 2'b10);

    // ---- frame shift register ----
    logic [10:0] shreg;
    logic [3:0]  bitcnt;
    logic [$clog2(IDLE_LIMIT+1)-1:0] idle_cnt;

    logic        frame_done;
    logic [7:0]  frame_data;
    logic        frame_ok;

    assign frame_data = shreg[8:1];
    // Odd parity over the eight data bits plus the parity bit, a zero start
    // bit and a one stop bit.
    assign frame_ok   = (shreg[0] == 1'b0) && (shreg[10] == 1'b1) &&
                        (^shreg[9:1] == 1'b1);

    // ---- FIFO ----
    localparam int DEPTH = 8;
    // 8 x 8 bits = 64 bits. Left to itself Quartus infers an M10K for this and
    // then bolts pass-through logic onto it to reproduce the read-during-write
    // behaviour -- spending a whole 10 Kbit block, plus ALMs, to be slower
    // than the flops it replaced. Registers are the right home for a FIFO this
    // small, and the read port stays genuinely combinational.
    (* ramstyle = "logic" *) logic [7:0] fifo [0:DEPTH-1];
    logic [2:0] head, tail;
    logic [3:0] count;

    logic pop;
    assign pop        = sel && rd && (port == 1'b0) && (count != 4'd0);
    assign data_avail = (count != 4'd0);

    // IRQ IS A LEVEL, NOT A PULSE. The interrupt controller samples its
    // external INT pins combinationally and latches nothing
    // (interrupt_controller.sv: request[S_INT0] = int0), so a one-clock pulse
    // is only seen if the CPU happens to be at an interruptible instruction
    // boundary that exact cycle. It usually is not, and the keystroke is lost
    // -- intermittently, which is the worst way for it to fail.
    //
    // Holding it asserted while a byte is pending is also what a real 8042
    // does, and it self-clears when software drains the FIFO. If more bytes
    // remain the request simply stays up and the handler is re-entered, which
    // is the behaviour a level-triggered input is supposed to have.
    assign irq = data_avail;
    assign rdata      = (port == 1'b0) ? fifo[head] : {7'h00, data_avail};

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            shreg      <= 11'h7FF;
            bitcnt     <= 4'd0;
            idle_cnt   <= '0;
            frame_done <= 1'b0;
            head       <= 3'd0;
            tail       <= 3'd0;
            count      <= 4'd0;
        end else begin
            frame_done <= 1'b0;

            // ---- receive ----
            if (falling) begin
                idle_cnt <= '0;
                shreg    <= {dat_sync, shreg[10:1]};
                if (bitcnt == 4'd10) begin
                    bitcnt     <= 4'd0;
                    frame_done <= 1'b1;
                end else begin
                    bitcnt <= bitcnt + 4'd1;
                end
            end else if (bitcnt != 4'd0) begin
                // Only time out mid-frame; an idle line between keys is normal.
                if (idle_cnt == IDLE_LIMIT[$bits(idle_cnt)-1:0]) begin
                    bitcnt   <= 4'd0;
                    idle_cnt <= '0;
                end else begin
                    idle_cnt <= idle_cnt + 1'b1;
                end
            end

            // ---- enqueue a good frame ----
            // A frame that fails parity or framing is dropped rather than
            // latched, so a corrupt byte never reaches software.
            if (frame_done && frame_ok && (count < DEPTH)) begin
                fifo[tail] <= frame_data;
                tail       <= tail + 3'd1;
                count      <= count + 4'd1 - {3'b0, pop};
            end else if (pop) begin
                count <= count - 4'd1;
            end

            if (pop) head <= head + 3'd1;
        end
    end

endmodule
