// ---------------------------------------------------------------------------
// pll — clock generation from the board's 50 MHz oscillator.
//
// Hierarchy: FPGA80186 -> clk_rst -> pll
//
// WHAT IT PRODUCES:
//   clk_sys   the CPU, SDRAM controller and everything else
//   clk_vga   the pixel clock, 25.175 MHz, independent of clk_sys
//   clk_dram  clk_sys phase-shifted, driven straight out to the memory
//
// WHY THE PHASE SHIFT IS THE POINT. Without a PLL this design ran at 25 MHz
// for one reason: DRAM_CLK was the inverted system clock driven out through
// the fabric, arriving at the memory about 4.5 ns late, after which the chip
// takes a further tAC of 5.4 ns to return read data. Inverting bought 20 ns of
// command setup at a 40 ns period, which is generous, and left the read data
// landing comfortably inside the capture window. At 20 ns it landed 2.4 ns
// PAST the capture edge, which is why 50 MHz was abandoned.
//
// A PLL lets the memory clock sit anywhere in the period rather than only at
// 0 or 180 degrees, and the two constraints pull in opposite directions:
//
//   later  -> more command/address setup at the memory
//   earlier-> read data comes back sooner, relative to our capture edge
//
// Ninety degrees splits them. At 40 MHz that is 6.25 ns of setup against a
// requirement of about 1.5 ns, and read data back around 18 ns into a 25 ns
// period. Both have real margin, which is the whole reason for doing this
// rather than simply asking for a faster clock and hoping.
//
// PLL_MODE PICKS WHERE THE CLOCKS COME FROM, NOT WHAT THEY ARE. That
// distinction was learned the hard way. The first version of this file tied
// the RATE to whether the vendor IP was present, so simulation ran at 25 MHz
// while hardware ran at 40 -- which meant the refresh interval, the timer
// prescaler and the BIOS's tick divisor all had to take two different values,
// and the one BIOS ROM in the tree could only ever be right for one of them.
// Modes 1 and 2 now produce the SAME frequencies by different means:
//
//   0  CLOCK_50 divided by two: 25 MHz for everything, the memory clock
//      inverted. The historical no-PLL build, kept because it is the fallback
//      if the PLL is ever suspected.
//   1  the Quartus-generated IP. Synthesises; cannot be simulated without
//      vendor libraries.
//   2  a behavioural model of mode 1 at the same three frequencies. Does not
//      synthesise. This is what every simulation runs, so the testbenches
//      exercise the clock rate the board will actually use.
// ---------------------------------------------------------------------------

`timescale 1ns/1ps
module pll #(
    parameter int PLL_MODE = 2
) (
    input  logic clk_board,          // CLOCK_50
    input  logic rst_btn_n,          // raw KEY[0]; resets the PLL itself
    output logic clk_sys,
    output logic clk_vga,
    output logic clk_dram,
    output logic locked
);

    generate
        if (PLL_MODE == 1) begin : g_pll
            // sys_pll is generated by Quartus's own IP tool, not hand-written:
            //
            //   ip-generate --component-name=altera_pll --output-name=sys_pll \
            //     --file-set=QUARTUS_SYNTH --output-dir=ip/sys_pll \
            //     --report-file=qip:ip/sys_pll/sys_pll.qip \
            //     --system-info=DEVICE_FAMILY="Cyclone V" \
            //     --system-info=DEVICE=5CSEMA5F31C6 \
            //     --component-param=gui_reference_clock_frequency=50.0 \
            //     --component-param=gui_operation_mode=direct \
            //     --component-param=gui_number_of_clocks=3 \
            //     --component-param=gui_use_locked=1 \
            //     --component-param=gui_output_clock_frequency0=40.0 \
            //     --component-param=gui_output_clock_frequency1=25.175 \
            //     --component-param=gui_output_clock_frequency2=40.0 \
            //     --component-param=gui_ps_units2=degrees \
            //     --component-param=gui_phase_shift_deg2=90.0
            //
            // Going through the IP tool rather than instantiating altera_pll
            // directly is what makes the three outputs ONE physical PLL with
            // three output counters, sharing a VCO and a feedback path. Three
            // separately instantiated PLLs would each lock independently, and
            // the 90-degree relationship between clk_sys and clk_dram -- the
            // entire reason for doing this -- would be meaningless. The tool
            // also reports what it can actually hit: outclk1 comes out at
            // 25.185185 MHz rather than 25.175, which is 0.04% fast and
            // invisible on a monitor.
            //
            // The PLL's own reset is the raw button. It cannot come from
            // clk_rst's reset, because that waits on `locked` and the two
            // would deadlock; and leaving it tied off means a PLL that ever
            // loses lock never recovers.
            sys_pll u_pll (
                .refclk   (clk_board),
                .rst      (~rst_btn_n),
                .outclk_0 (clk_sys),
                .outclk_1 (clk_vga),
                .outclk_2 (clk_dram),
                .locked   (locked)
            );
        end else if (PLL_MODE == 2) begin : g_behavioural
            // The same rates mode 1 produces, generated directly. Free
            // running and unrelated to clk_board, exactly as a real PLL's
            // outputs are unrelated to its reference once locked.
            //   40 MHz        -> 12.5 ns half period
            //   25.185185 MHz -> 19.853 ns half period
            //   clk_dram      -> 40 MHz, a quarter period (6.25 ns) late
            logic sys_b = 1'b0, vga_b = 1'b0, dram_b = 1'b0;
            initial forever #12.500 sys_b = ~sys_b;
            initial forever #19.853 vga_b = ~vga_b;
            initial begin
                #6.250;
                forever #12.500 dram_b = ~dram_b;
            end

            // Lock is modelled rather than tied high, because clk_rst holds
            // the design in reset until it asserts and that path should be
            // exercised somewhere.
            logic locked_b = 1'b0;
            initial begin
                #1000;
                locked_b = 1'b1;
            end

            assign clk_sys  = sys_b;
            assign clk_vga  = vga_b;
            assign clk_dram = dram_b;
            assign locked   = locked_b;
        end else begin : g_divider
            // The no-PLL arrangement this design used throughout: one 25 MHz
            // clock for everything, and the memory clock inverted to buy
            // command setup.
            logic div;
            initial div = 1'b0;
            always_ff @(posedge clk_board) div <= ~div;
            assign clk_sys  = div;
            assign clk_vga  = div;
            assign clk_dram = ~div;
            assign locked   = 1'b1;
        end
    endgenerate

endmodule
