# ---------------------------------------------------------------------------
# FPGA80186 timing constraints (DE1-SoC, Cyclone V).
#
# CLOCK_50 enters the chip and a PLL (ip/sys_pll, generated by Quartus's IP
# tool -- see modules/pll.sv) produces three clocks from it:
#
#   outclk_0  40 MHz       clk_cpu   the CPU, the cache, the SDRAM controller
#   outclk_1  25.185 MHz   clk_vga   the pixel clock
#   outclk_2  40 MHz @ 90  clk_dram  driven straight out to the memory
#
# derive_pll_clocks creates all three; they must not be declared by hand as
# well, or they get constrained twice and the analysis becomes meaningless.
#
# Only the reset debouncer and the power-on counter remain in the raw 50 MHz
# domain, and nothing crosses between domains synchronously -- the reset they
# produce is applied asynchronously and analysed as recovery and removal.
# ---------------------------------------------------------------------------

create_clock -name CLOCK_50 -period 20.000 [get_ports CLOCK_50]

derive_pll_clocks
derive_clock_uncertainty

# ---------------------------------------------------------------------------
# Clock domain crossings.
#
# THIS IS NEW WITH THE PLL AND IT MATTERS. Before, clk_vga WAS clk_cpu -- one
# net, divided from CLOCK_50 -- so signals between them were not crossings at
# all. Now they are separate PLL outputs at unrelated rates, and everything
# that passes between them goes through a synchroniser (see the cursor and
# mode_gfx paths in vga_controller.sv). Those are deliberately unanalysable as
# single-cycle paths, so they are cut here. Cutting them without the
# synchronisers in place would simply hide the problem.
# ---------------------------------------------------------------------------
# THE NAMES MATTER AND THEY ARE NOT THE OBVIOUS ONES. derive_pll_clocks names
# each output "...|general[N].gpll~PLL_OUTPUT_COUNTER|divclk" -- with a tilde
# section that does not appear anywhere in the RTL. A pattern without it
# matches nothing, and Quartus does not treat that as an error: it warns
# "contains zero elements" and carries on with the crossings timed as though
# they were synchronous. That is how the first PLL build came out reporting a
# 1.355 ns violation in the video domain that did not exist. The wildcards
# below span the tilde section deliberately, and get_pins needs
# -compatibility_mode before a wildcard will cross a "|" at all.
# A second trap on top of the names: `concat` of two collections yields the
# collection HANDLES ("_col15 _col17"), not their contents, and set_clock_groups
# then reports those as unmatched clock names. Both patterns go in one
# get_clocks call instead.
set_clock_groups -asynchronous \
    -group [get_clocks {*general[0].gpll*divclk *general[2].gpll*divclk}] \
    -group [get_clocks {*general[1].gpll*divclk}] \
    -group [get_clocks CLOCK_50]

# Asynchronous or non-timing-critical I/O.
set_false_path -from [get_ports {KEY[*]}] -to *
set_false_path -from [get_ports PS2_CLK]  -to *
set_false_path -from [get_ports PS2_DAT]  -to *
set_false_path -from * -to [get_ports {LEDR[*]}]

# VGA outputs feed the ADV7123 DAC. A proper build would constrain these
# against the DAC's setup/hold window; false-pathing them is acceptable for a
# first bring-up build but should be revisited before trusting the picture at
# higher pixel clocks.
set_false_path -from * -to [get_ports {VGA_R[*]}]
set_false_path -from * -to [get_ports {VGA_G[*]}]
set_false_path -from * -to [get_ports {VGA_B[*]}]
set_false_path -from * -to [get_ports VGA_HS]
set_false_path -from * -to [get_ports VGA_VS]
set_false_path -from * -to [get_ports VGA_CLK]
set_false_path -from * -to [get_ports VGA_BLANK_N]
set_false_path -from * -to [get_ports VGA_SYNC_N]

# ---------------------------------------------------------------------------
# SDRAM interface (IS42S16320D-7TL, 32M x 16, on the DE1-SoC).
#
# DRAM_CLK is now the PLL's third output driven straight out through the pin,
# rather than `~clk` through the fabric. It still has to be DECLARED as a
# generated clock or the analyser treats it as ordinary data and times nothing
# against it.
#
# These delays are not decoration. Before they were added the entire memory
# interface was unconstrained, so STA reported no margin for it and the build
# looked clean while the read path was in fact missing its capture edge. That
# violation is what set the system clock at 25 MHz rather than 50; the 90
# degree shift is what buys it back at 40.
#
# Datasheet numbers for the -7 speed grade:
#   tAC 5.4 ns   clock -> data valid    (read, worst case)
#   tOH 2.7 ns   data hold after clock  (read)
#   tSU 1.5 ns   input setup            (write/command)
#   tHD 0.8 ns   input hold             (write/command)
#
# Board trace delay is ignored; the DE1-SoC traces are short and every
# DE-series reference constraint set does the same.
# ---------------------------------------------------------------------------
# Same naming trap as above, and worse here: if this source does not match,
# DRAM_CLK is never created at all and the whole memory interface goes
# UNCONSTRAINED -- which reports as a clean build while the read capture may be
# missing its edge entirely. That exact failure is what pinned this design at
# 25 MHz before the interface was constrained the first time.
create_generated_clock -name DRAM_CLK \
    -source [get_pins -compatibility_mode {*general[2].gpll*divclk}] \
    [get_ports DRAM_CLK]

set sdram_outs [get_ports {DRAM_ADDR[*] DRAM_BA[*] DRAM_DQ[*] \
                           DRAM_CKE DRAM_CS_N DRAM_RAS_N DRAM_CAS_N \
                           DRAM_WE_N DRAM_LDQM DRAM_UDQM}]

set_output_delay -clock DRAM_CLK -max  1.5 $sdram_outs
set_output_delay -clock DRAM_CLK -min -0.8 $sdram_outs

set_input_delay  -clock DRAM_CLK -max  5.4 [get_ports {DRAM_DQ[*]}]
set_input_delay  -clock DRAM_CLK -min  2.7 [get_ports {DRAM_DQ[*]}]
