`timescale 1ns/1ns
//
// The whole machine, running the real boot ROM.
//
// Nothing here is stubbed or forced: the BIOS image is the one tools/gen_bios.py
// produced, the glyph data is the one tools/gen_font.py extracted, conventional
// RAM is the SDRAM model, and the video path is the real scan-out. The test
// releases reset and then reads back what ended up in the text buffer.
//
// This is the check that the earlier module tests cannot make. tb_vga forces
// its own glyphs and tb_top supplies its own hand-written program, so both
// would still pass if the ROM images were empty or wired to the wrong path.
//
module tb_bios;

    logic       CLOCK_50 = 0;
    logic [0:0] KEY = 1'b1;
    logic [9:0] LEDR;
    logic [7:0] VGA_R, VGA_G, VGA_B;
    logic       VGA_HS, VGA_VS, VGA_CLK, VGA_BLANK_N, VGA_SYNC_N;
    logic       PS2_CLK = 1'b1, PS2_DAT = 1'b1;
    logic [12:0] DRAM_ADDR;
    logic [1:0]  DRAM_BA;
    wire  [15:0] DRAM_DQ;
    logic        DRAM_CKE, DRAM_CS_N, DRAM_RAS_N, DRAM_CAS_N, DRAM_WE_N;
    logic        DRAM_LDQM, DRAM_UDQM, DRAM_CLK;

    // The JTAG loader holds an Altera primitive that cannot be simulated.
    FPGA80186 #(.ENABLE_JTAG_LOADER(1'b0)) dut (.*);
    defparam dut.u_clk_rst.DEBOUNCE = 20;
    defparam dut.u_mem.SDRAM_INIT_CYCLES = 40;

    sdram_model #(.CAS_LATENCY(2)) chip (
        .dram_clk (DRAM_CLK), .dram_cke (DRAM_CKE), .dram_cs_n (DRAM_CS_N),
        .dram_ras_n (DRAM_RAS_N), .dram_cas_n (DRAM_CAS_N), .dram_we_n (DRAM_WE_N),
        .dram_addr (DRAM_ADDR), .dram_ba (DRAM_BA),
        .dram_dqm ({DRAM_UDQM, DRAM_LDQM}), .dram_dq (DRAM_DQ)
    );

    always #10 CLOCK_50 = ~CLOCK_50;

    // Generated by tools/gen_disk.py; see sim/tb_storage.sv.
    `include "geometry.svh"

    // ---- where the CPU's cycles actually go ----
    // Not a check: a measurement, so that "would a cache help" has an answer
    // rather than an opinion. A cycle counts as stalled when the CPU has a bus
    // request outstanding and the memory has not answered yet.
    int cyc_total = 0, stall_ram = 0, stall_other = 0, bus_cycles = 0;
    always @(posedge dut.clk_cpu) begin
        cyc_total++;
        if (dut.rd || dut.wr) begin
            bus_cycles++;
            if (!dut.ready) begin
                if (dut.u_mem.in_ram) stall_ram++;
                else                  stall_other++;
            end
        end
    end

    // ---- how many cycles an instruction actually costs ----
    // CPI is the number that decides whether a branch predictor or a
    // prefetcher is worth building: if the execution unit is spending ten
    // cycles per instruction internally, shaving a few off the fetch path
    // cannot matter much. Counted from the microcode sequencer's retire
    // state, the same signal the MS-DOS trace uses.
    localparam logic [5:0] ST_RETIRE = 6'd18;
    // HALTED CYCLES ARE NOT WORK. Most of this run is the machine parked in
    // HLT waiting for keystrokes, and counting those gave a CPI of 160 --
    // a number that says nothing except that the testbench waits a long time.
    int retired = 0, busy_cycles = 0;
    logic [5:0] prev_exec = 6'd0;
    always @(posedge dut.clk_cpu) begin
        if (!dut.halted) busy_cycles++;
        if (dut.u_cpu.u_eu.u_exec.state == ST_RETIRE && prev_exec != ST_RETIRE)
            retired++;
        prev_exec <= dut.u_cpu.u_eu.u_exec.state;
    end

    // ---- decode_len shadow, fast iteration ----
    // Same check tb_msdos runs, here because this testbench finishes in a
    // minute rather than eleven. Prints the offending bytes, which is the
    // only way to tell a wrong rule from a wrong measurement.
    logic [7:0] dl_peek [0:5];
    logic [3:0] dl_count;
    logic       dl_valid;
    logic [2:0] dl_len, dl_npfx;
    logic       dl_rep, dl_seg;
    logic [1:0] dl_segovr;

    always_comb begin
        for (int i = 0; i < 6; i++) dl_peek[i] = dut.u_cpu.u_biu.u_pq.peek[i];
        dl_count = dut.u_cpu.u_biu.u_pq.count;
    end

    decode_len u_dl (
        .peek (dl_peek), .count (dl_count), .valid (dl_valid),
        .len (dl_len), .n_prefix (dl_npfx),
        .has_rep (dl_rep), .has_seg_ovr (dl_seg), .seg_ovr (dl_segovr)
    );

    localparam logic [5:0] ST_FETCH_OP = 6'd1;
    int dl_checked = 0, dl_mismatch = 0, dl_unknown = 0;
    logic       dl_armed = 1'b0;
    logic [2:0] dl_pred;
    logic [7:0] dl_b [0:5];
    int         dl_bytes;
    logic [5:0] dl_prev = 6'd0;

    // The #1 is not cosmetic. dl_peek is driven by an always_comb and
    // decode_len's outputs are another delta behind it, so reading them from
    // a different always block at the same instant samples stale values --
    // which showed up as a one-byte instruction being predicted as three.
    always @(negedge dut.clk_cpu) begin
        #1;
        if (dut.u_cpu.u_eu.u_exec.state == ST_FETCH_OP && dl_prev != ST_FETCH_OP
            && !dut.u_cpu.u_eu.u_exec.prefix_seen) begin
            dl_bytes = 0;
            if (dl_valid) begin
                dl_armed = 1'b1;
                dl_pred  = dl_len;
                for (int i = 0; i < 6; i++) dl_b[i] = dl_peek[i];
            end else begin
                dl_armed = 1'b0;
                dl_unknown++;
            end
        end
        if (dl_armed) dl_bytes = dl_bytes + dut.u_cpu.u_biu.u_pq.do_pop;
        if (dut.u_cpu.u_eu.u_exec.state == ST_RETIRE && dl_prev != ST_RETIRE) begin
            if (dl_armed) begin
                dl_checked++;
                if (dl_bytes != {29'd0, dl_pred}) begin
                    if (dl_mismatch < 12)
                        $display("  DL MISMATCH pred=%0d popped=%0d bytes: %02h %02h %02h %02h %02h %02h",
                                 dl_pred, dl_bytes,
                                 dl_b[0], dl_b[1], dl_b[2], dl_b[3], dl_b[4], dl_b[5]);
                    dl_mismatch++;
                end
            end
            dl_armed = 1'b0;
        end
        dl_prev = dut.u_cpu.u_eu.u_exec.state;
    end

    int errors = 0, checks = 0;
    task chk(input string nm, input int got, input int exp);
        checks++;
        if (got !== exp) begin
            $display("FAIL %-40s got=%04h exp=%04h", nm, got, exp);
            errors++;
        end
    endtask

    // Character and attribute for text cell n.
    function automatic [7:0] cell_ch(input int n);
        cell_ch = dut.u_mem.u_vram.ram_lo[n];
    endfunction
    function automatic [7:0] cell_at(input int n);
        cell_at = dut.u_mem.u_vram.ram_hi[n];
    endfunction

    // Every line the boot is expected to paint, in order. Lines 0-2 come from
    // the BIOS in ROM; line 3 exists only on the disk, so seeing it proves the
    // whole chain ran: INT 19h -> INT 13h -> storage -> jump to 0000:7C00 ->
    // the loaded code calling INT 10h.
    string want [0:6] = '{
        "FPGA80186 BIOS -- 640K, VGA text, PS/2 keyboard, block storage.",
        "Booting from disk 0...",
        "Boot sector loaded, starting.",
        "Loading KERNEL.BIN",
        "Starting kernel.",
        "KERNEL.BIN loaded from FAT12 and running.",
        "hello"
    };


    string got;
    int i, r, glyph_bits;
    logic [15:0] bda, tail_before, tail_after, kb_entry;

    // ---- PS/2 frame injection, straight at the board pins ----
    task ps2_bit(input logic b);
        begin
            PS2_DAT = b;
            repeat (30) @(posedge CLOCK_50);
            PS2_CLK = 1'b0;
            repeat (30) @(posedge CLOCK_50);
            PS2_CLK = 1'b1;
            repeat (30) @(posedge CLOCK_50);
        end
    endtask

    task ps2_byte(input [7:0] code);
        logic p;
        begin
            p = ~(^code);                  // odd parity
            ps2_bit(1'b0);
            for (int k = 0; k < 8; k++) ps2_bit(code[k]);
            ps2_bit(p);
            ps2_bit(1'b1);
            repeat (60) @(posedge CLOCK_50);
        end
    endtask

    // A REAL KEYSTROKE, press and release. This used to send only the make
    // code, which is not what a keyboard does and is not what the BIOS has to
    // cope with: every key also sends a release, and the handler has to
    // recognise and discard it. Testing only the press left the entire
    // release path unexercised through the BIOS -- so a bug that made typing
    // lag several characters behind could pass every test here.
    task ps2_key(input [7:0] code);
        begin
            ps2_byte(code);                // make
            ps2_byte(8'hF0);               // break prefix (set 2, off the wire)
            ps2_byte(code);                // ...and the code again
        end
    endtask

    function automatic string read_line(input int row, input int len);
        string t = "";
        for (int c = 0; c < len; c++) t = {t, string'(cell_ch(row * 80 + c))};
        return t;
    endfunction

    initial begin
        repeat (10) @(negedge CLOCK_50);
        KEY[0] = 1'b0;
        repeat (100) @(negedge CLOCK_50);
        KEY[0] = 1'b1;

        // The boot sector prints, then blocks in INT 16h waiting for five
        // keystrokes. Wait until it is actually blocked -- the BIOS parks in
        // HLT with interrupts enabled, which is what makes wake-on-interrupt
        // load-bearing here rather than decorative.
        i = 0;
        while (!dut.halted && i < 8000000) begin @(negedge CLOCK_50); i++; end
        $display("  boot to the keyboard wait: %0d CLOCK_50 cycles", i);
        chk("machine reached the keyboard wait", dut.halted, 1'b1);

        // "hello" in PS/2 scancode set 2. Nothing is forced: these are real
        // 11-bit frames clocked in at PS2_CLK/PS2_DAT.
        ps2_key(8'h33);   // h
        ps2_key(8'h24);   // e
        ps2_key(8'h4B);   // l
        ps2_key(8'h4B);   // l
        ps2_key(8'h44);   // o

        // After the fifth key the boot sector falls out of its loop and halts
        // for good.
        i = 0;
        // Long enough for the kernel to finish echoing AND to run the
        // graphics block after it. Clearing the 64,000-byte aperture is
        // 32,000 word writes -- around 320,000 CPU clocks, which is nothing
        // on hardware and dominates this wait.
        while (i < 5000000) begin @(negedge CLOCK_50); i++; end
        chk("machine reached the boot sector's HLT", dut.halted, 1'b1);

        // ---- the bottom of the screen scrolls ----
        // The kernel put a marker on row 24, homed the cursor there and
        // printed a newline. The BIOS's newline path has to scroll, and its
        // scroll routine takes a window and a line count in registers that
        // the caller must set. It did not, so output at the bottom overwrote
        // the last line. Everything on screen has therefore moved up one row,
        // which is what the line comparison below now expects.
        chk("the last row scrolled up one", cell_ch(23*80 + 0), 8'h51);
        // The vacated row is not checked here: the kernel echoes "hello"
        // into it straight afterwards. The blanking is covered by the
        // explicit AH=06 scroll further down.

        // ---- INT 10h AH=06 honours AL and the window rectangle ----
        // The kernel filled rows 10..14 with 'X', then asked for the window
        // rows 11..13 / columns 10..20 to be blanked with attribute 1F.
        // Everything outside that rectangle must be untouched -- the old
        // implementation ignored the arguments entirely and scrolled the
        // whole screen one line, which is why CLS did not clear.
        chk("blanked inside the window",        cell_ch(11*80 + 10), 8'h20);
        chk("...with the requested attribute",  cell_at(11*80 + 10), 8'h1F);
        chk("blanked to the window's last row", cell_ch(13*80 + 20), 8'h20);
        chk("row above the window untouched",   cell_ch(10*80 + 10), 8'h58);
        chk("row below the window untouched",   cell_ch(14*80 + 10), 8'h58);
        chk("column left of the window kept",   cell_ch(11*80 +  9), 8'h58);
        chk("column right of the window kept",  cell_ch(11*80 + 21), 8'h58);

        // ...and AL=1 really scrolls by one line rather than blanking.
        chk("scroll moved row 21 up to row 20", cell_ch(20*80 + 0), 8'h42);
        chk("scroll moved row 22 up to row 21", cell_ch(21*80 + 0), 8'h43);
        chk("scroll blanked the vacated row",   cell_ch(22*80 + 0), 8'h20);
        chk("...with the requested attribute",  cell_at(22*80 + 0), 8'h20);

        // ---- modifier state, and keys that have no ASCII ----
        // The machine is halted, but HLT wakes on an interrupt, so INT 09h
        // still runs and nothing is consuming the buffer any more -- which
        // makes this the easiest place to look at what the handler actually
        // stored.
        //
        // Ctrl and Alt were never tracked at all: only Shift wrote 40:17, so
        // INT 16h AH=02 reported them permanently released and QBASIC, which
        // opens its menus with Alt, could not be driven.
        ps2_byte(8'h14);                        // Ctrl down (set 2 14 -> 1D)
        repeat (80000) @(posedge CLOCK_50);   // > one 1 ms frame time
        bda = chip.mem['h416 >> 1];
        chk("Ctrl sets bit 2 of 40:17", bda[15:8] & 8'h04, 8'h04);

        ps2_byte(8'h11);                        // Alt down (set 2 11 -> 38)
        repeat (80000) @(posedge CLOCK_50);   // > one 1 ms frame time
        bda = chip.mem['h416 >> 1];
        chk("Alt sets bit 3, Ctrl still held", bda[15:8] & 8'h0C, 8'h0C);

        ps2_byte(8'hF0); ps2_byte(8'h11);       // Alt up
        repeat (80000) @(posedge CLOCK_50);   // > one 1 ms frame time
        bda = chip.mem['h416 >> 1];
        chk("releasing Alt clears only its bit", bda[15:8] & 8'h0C, 8'h04);

        ps2_byte(8'hF0); ps2_byte(8'h14);       // Ctrl up
        repeat (80000) @(posedge CLOCK_50);   // > one 1 ms frame time
        bda = chip.mem['h416 >> 1];
        chk("releasing Ctrl clears bit 2", bda[15:8] & 8'h04, 8'h00);

        // A modifier must not deliver a keystroke of its own.
        tail_before = chip.mem['h41C >> 1];
        ps2_byte(8'h12); ps2_byte(8'hF0); ps2_byte(8'h12);   // shift, tapped
        repeat (160000) @(posedge CLOCK_50);  // two frame times
        chk("tapping Shift enqueued nothing", chip.mem['h41C >> 1], tail_before);

        // An arrow has no ASCII, and used to be thrown away for that reason --
        // which left an editor with no way to move its cursor. A PC BIOS
        // delivers it as AH = scancode, AL = 00.
        tail_before = chip.mem['h41C >> 1];
        ps2_byte(8'hE0); ps2_byte(8'h75);       // Up
        repeat (160000) @(posedge CLOCK_50);  // two frame times
        tail_after = chip.mem['h41C >> 1];
        checks++;
        if (tail_after === tail_before) begin
            $display("FAIL an arrow key was dropped instead of enqueued");
            errors++;
        end else begin
            kb_entry = chip.mem[('h400 + tail_before) >> 1];
            chk("Up arrow delivers scancode 48 with no ASCII",
                kb_entry, 16'h4800);
        end
        chk("halt is visible on LEDR[7]", LEDR[7], 1'b1);
        chk("no unexpected trap was taken", dut.dbg_int_taken, 1'b0);

        $display("");
        // Row r now holds what was printed as line r+1: the whole screen
        // moved up when the kernel forced a scroll, and the banner scrolled
        // off the top. Seeing "Booting from disk 0..." at row 0 proves both
        // that the ROM ran and that the scroll happened.
        // want[6] ("hello") is no longer on line 6: the scroll left the
        // cursor on the last row, so the echo lands there instead.
        for (r = 0; r <= 4; r++) begin
            got = read_line(r, want[r + 1].len());
            $display("  line %0d: \"%s\"", r, got);
            checks++;
            if (got != want[r + 1]) begin
                $display("FAIL line %0d mismatch", r);
                $display("    expected: \"%s\"", want[r + 1]);
                errors++;
            end
        end
        $display("");

        // ---- the BIOS data area was set up ----
        // The BDA lives at segment 0040, so 40:10 is physical 0410. chip.mem is
        // word-addressed, and 40:13 is an ODD offset, so the memory-size word
        // straddles two of those words.
        chk("equipment word",  chip.mem['h410 >> 1], 16'h0021);
        chk("memory size, KB",
            {chip.mem['h414 >> 1][7:0], chip.mem['h413 >> 1][15:8]}, 16'd640);

        // ---- the interrupt vector table points into the BIOS ----
        chk("INT 10h vector segment", chip.mem[('h10*4 + 2) >> 1], 16'hF000);
        chk("INT 13h vector segment", chip.mem[('h13*4 + 2) >> 1], 16'hF000);
        chk("INT 16h vector segment", chip.mem[('h16*4 + 2) >> 1], 16'hF000);
        // An unused vector must still be filled, or a stray interrupt would
        // run whatever happened to be in RAM.
        chk("unused vector filled",   chip.mem[('h40*4 + 2) >> 1], 16'hF000);

        // ---- the boot sector really was loaded where a boot sector goes ----
        chk("boot signature at 0000:7DFE", chip.mem['h7DFE >> 1], 16'hAA55);
        checks++;
        if (chip.mem['h7C00 >> 1] === 16'h0000) begin
            $display("FAIL nothing was loaded at 0000:7C00");
            errors++;
        end

        // ---- the cursor followed the text ----
        // Four lines were printed, so the CRTC cursor must sit on row 4.
        chk("the echo landed on the last row", read_line(24, 5) == want[6], 1'b1);
        // ...and the cursor followed it there: row 24, column 5.
        chk("cursor tracked the text", dut.u_crtc.cursor_addr, 11'd1925);
        chk("cursor still enabled", dut.u_crtc.cursor_en, 1'b1);

        // ---- the font image really loaded ----
        glyph_bits = 0;
        for (i = 0; i < 16; i++)
            glyph_bits += $countones(dut.u_vga.u_font.g_inferred.rom[{8'h41, i[3:0]}]);
        checks++;
        if (glyph_bits == 0) begin
            $display("FAIL font ROM is empty -- the image did not load");
            errors++;
        end

        // INT 13h AH=08, as the kernel left it at 0000:0600. Reporting the
        // last cylinder rather than the count is the part that is easy to get
        // wrong, and a BIOS that claims one cylinder describes a disk one
        // track long.
        chk("INT 13h AH=08 last cylinder and sectors per track",
            chip.mem['h600 >> 1], {8'((GEO_BIOS_CYLS - 1)), 8'(GEO_SPT)});
        chk("INT 13h AH=08 last head and drive count",
            chip.mem['h602 >> 1], {8'((GEO_HEADS - 1)), 8'd1});

        // ---- INT 13h AH=03 against a READ-ONLY disk ----
        // This build backs the disk with ROM, which has nowhere to put a
        // write. The point is that it fails cleanly and says so: storage.sv
        // raises ERR rather than pretending, and the BIOS turns that into a
        // non-zero AH instead of hanging in its BUSY poll. tb_bios_sdramdisk
        // covers the case where the write is supposed to succeed.
        checks++;
        if (chip.mem['h604 >> 1][7:0] === 8'h00) begin
            $display("FAIL INT 13h AH=03 claimed success on a read-only disk");
            errors++;
        end

        // ---- graphics mode, set and drawn by the loaded kernel ----
        // Read straight out of the framebuffer and the palette the video
        // controller scans, so this covers INT 10h mode 13h, the A0000
        // decode, the byte lanes and the 3C8/3C9 DAC in one go.
        chk("mode register selected graphics", dut.mode_gfx, 1'b1);
        // ...and the BIOS's read-back of port 3D8 must agree with it. The BDA
        // mode byte is only the BIOS's opinion; this is the hardware's.
        chk("BIOS read the mode register back as graphics",
            chip.mem['h480 >> 1][7:0], 8'h02);
        chk("kernel plotted pixel (0,0)",   dut.u_mem.u_fb.ram_lo[0], 8'h01);
        chk("kernel plotted pixel (1,0)",   dut.u_mem.u_fb.ram_hi[0], 8'h02);
        // 199*320 + 319 = 63999, an odd offset, so it lands in the high lane
        // of word 31999 -- which is what makes it a byte-lane check too.
        chk("kernel plotted the last pixel", dut.u_mem.u_fb.ram_hi[31999], 8'h03);
        // Bar 3 covers x=48..63 of every row, so row 1 pixel 50 must be the
        // bar index -- which also proves the row-replicating REP MOVSW ran.
        chk("colour bars replicated down the screen",
            dut.u_mem.u_fb.ram_lo[(320 + 50) >> 1], 8'd3);
        // ---- the blitter, driven by the loaded kernel ----
        // Read straight out of the framebuffer the video controller scans, so
        // this covers the 0330 port decode, the register file, the shared
        // framebuffer port and the byte lanes from software down.
        chk("blitter filled the first pixel of its rectangle",
            dut.u_mem.u_fb.ram_hi[(100*320 + 1) >> 1], 8'h2A);
        chk("blitter filled the last pixel of the last row",
            dut.u_mem.u_fb.ram_lo[(100*320 + 1 + 7*320 + 15) >> 1], 8'h2A);
        chk("blitter left the pixel before the rectangle alone",
            dut.u_mem.u_fb.ram_lo[(100*320) >> 1], 8'd0);
        // The kernel's own verdict, which is what the hardware check reads
        // back over JTAG since the framebuffer is on-chip and invisible to it.
        chk("the kernel's own blitter self-check passed",
            chip.mem['h604 >> 1][7:0], 8'hA0);   // 604 is even: low lane

        chk("blitter copied the rectangle elsewhere",
            dut.u_mem.u_fb.ram_lo[(120*320 + 2) >> 1], 8'h2A);
        chk("the copy's last row arrived too",
            dut.u_mem.u_fb.ram_hi[(120*320 + 2 + 7*320 + 15) >> 1], 8'h2A);

        chk("palette entry 1 loaded through 3C8/3C9",
            dut.u_dac.pal[1], 18'({6'd63, 6'd0, 6'd0}));

        chk("no SDRAM protocol errors", chip.errors, 0);

        $display("");
        $display("  %0d cycles, %0d with a bus request (%0.1f%%)",
                 cyc_total, bus_cycles, 100.0 * bus_cycles / cyc_total);
        $display("  stalled waiting on SDRAM:     %0d (%0.1f%%)",
                 stall_ram, 100.0 * stall_ram / cyc_total);
        $display("  stalled waiting on ROM/other: %0d (%0.1f%%)",
                 stall_other, 100.0 * stall_other / cyc_total);
        $display("");
        $display("  %0d instructions in %0d running cycles (%0d total)",
                 retired, busy_cycles, cyc_total);
        $display("  CPI %0.2f   bus-request cycles %0.1f%%   stalled on RAM %0.1f%%",
                 real'(busy_cycles) / real'(retired),
                 100.0 * bus_cycles / busy_cycles,
                 100.0 * stall_ram / busy_cycles);
        $display("");
        $display("  decode_len shadow: %0d checked, %0d mismatched, %0d unknowable",
                 dl_checked, dl_mismatch, dl_unknown);
        $display("");
        $display("==================================");
        $display(" checks: %0d   failures: %0d", checks, errors);
        $display("==================================");
        if (errors == 0) $display("ALL TESTS PASSED");
        $finish;
    end

    initial begin
        #400000000;
        $display("FAIL global timeout (IP=%04h halted=%b)", dut.dbg_ip, dut.halted);
        $display(" checks: %0d   failures: %0d", checks, errors + 1);
        $finish;
    end

endmodule
