`timescale 1ns/1ns
//
// The whole machine, running the real boot ROM.
//
// Nothing here is stubbed or forced: the BIOS image is the one tools/gen_bios.py
// produced, the glyph data is the one tools/gen_font.py extracted, conventional
// RAM is the SDRAM model, and the video path is the real scan-out. The test
// releases reset and then reads back what ended up in the text buffer.
//
// This is the check that the earlier module tests cannot make. tb_vga forces
// its own glyphs and tb_top supplies its own hand-written program, so both
// would still pass if the ROM images were empty or wired to the wrong path.
//
module tb_bios;

    logic       CLOCK_50 = 0;
    logic [0:0] KEY = 1'b1;
    logic [9:0] LEDR;
    logic [7:0] VGA_R, VGA_G, VGA_B;
    logic       VGA_HS, VGA_VS, VGA_CLK, VGA_BLANK_N, VGA_SYNC_N;
    logic       PS2_CLK = 1'b1, PS2_DAT = 1'b1;
    logic [12:0] DRAM_ADDR;
    logic [1:0]  DRAM_BA;
    wire  [15:0] DRAM_DQ;
    logic        DRAM_CKE, DRAM_CS_N, DRAM_RAS_N, DRAM_CAS_N, DRAM_WE_N;
    logic        DRAM_LDQM, DRAM_UDQM, DRAM_CLK;

    // The JTAG loader holds an Altera primitive that cannot be simulated.
    FPGA80186 #(.ENABLE_JTAG_LOADER(1'b0)) dut (.*);
    defparam dut.u_clk_rst.DEBOUNCE = 20;
    defparam dut.u_mem.SDRAM_INIT_CYCLES = 40;

    sdram_model #(.CAS_LATENCY(2)) chip (
        .dram_clk (DRAM_CLK), .dram_cke (DRAM_CKE), .dram_cs_n (DRAM_CS_N),
        .dram_ras_n (DRAM_RAS_N), .dram_cas_n (DRAM_CAS_N), .dram_we_n (DRAM_WE_N),
        .dram_addr (DRAM_ADDR), .dram_ba (DRAM_BA),
        .dram_dqm ({DRAM_UDQM, DRAM_LDQM}), .dram_dq (DRAM_DQ)
    );

    always #10 CLOCK_50 = ~CLOCK_50;

    // Generated by tools/gen_disk.py; see sim/tb_storage.sv.
    `include "geometry.svh"

    // ---- where the CPU's cycles actually go ----
    // Not a check: a measurement, so that "would a cache help" has an answer
    // rather than an opinion. A cycle counts as stalled when the CPU has a bus
    // request outstanding and the memory has not answered yet.
    int cyc_total = 0, stall_ram = 0, stall_other = 0, bus_cycles = 0;
    always @(posedge dut.clk_cpu) begin
        cyc_total++;
        if (dut.rd || dut.wr) begin
            bus_cycles++;
            if (!dut.ready) begin
                if (dut.u_mem.in_ram) stall_ram++;
                else                  stall_other++;
            end
        end
    end

    int errors = 0, checks = 0;
    task chk(input string nm, input int got, input int exp);
        checks++;
        if (got !== exp) begin
            $display("FAIL %-40s got=%04h exp=%04h", nm, got, exp);
            errors++;
        end
    endtask

    // Character and attribute for text cell n.
    function automatic [7:0] cell_ch(input int n);
        cell_ch = dut.u_mem.u_vram.ram_lo[n];
    endfunction
    function automatic [7:0] cell_at(input int n);
        cell_at = dut.u_mem.u_vram.ram_hi[n];
    endfunction

    // Every line the boot is expected to paint, in order. Lines 0-2 come from
    // the BIOS in ROM; line 3 exists only on the disk, so seeing it proves the
    // whole chain ran: INT 19h -> INT 13h -> storage -> jump to 0000:7C00 ->
    // the loaded code calling INT 10h.
    string want [0:6] = '{
        "FPGA80186 BIOS -- 640K, VGA text, PS/2 keyboard, block storage.",
        "Booting from disk 0...",
        "Boot sector loaded, starting.",
        "Loading KERNEL.BIN",
        "Starting kernel.",
        "KERNEL.BIN loaded from FAT12 and running.",
        "hello"
    };


    string got;
    int i, r, glyph_bits;

    // ---- PS/2 frame injection, straight at the board pins ----
    task ps2_bit(input logic b);
        begin
            PS2_DAT = b;
            repeat (30) @(posedge CLOCK_50);
            PS2_CLK = 1'b0;
            repeat (30) @(posedge CLOCK_50);
            PS2_CLK = 1'b1;
            repeat (30) @(posedge CLOCK_50);
        end
    endtask

    task ps2_key(input [7:0] code);
        logic p;
        begin
            p = ~(^code);                  // odd parity
            ps2_bit(1'b0);
            for (int k = 0; k < 8; k++) ps2_bit(code[k]);
            ps2_bit(p);
            ps2_bit(1'b1);
            repeat (60) @(posedge CLOCK_50);
        end
    endtask

    function automatic string read_line(input int row, input int len);
        string t = "";
        for (int c = 0; c < len; c++) t = {t, string'(cell_ch(row * 80 + c))};
        return t;
    endfunction

    initial begin
        repeat (10) @(negedge CLOCK_50);
        KEY[0] = 1'b0;
        repeat (100) @(negedge CLOCK_50);
        KEY[0] = 1'b1;

        // The boot sector prints, then blocks in INT 16h waiting for five
        // keystrokes. Wait until it is actually blocked -- the BIOS parks in
        // HLT with interrupts enabled, which is what makes wake-on-interrupt
        // load-bearing here rather than decorative.
        i = 0;
        while (!dut.halted && i < 8000000) begin @(negedge CLOCK_50); i++; end
        $display("  boot to the keyboard wait: %0d CLOCK_50 cycles", i);
        chk("machine reached the keyboard wait", dut.halted, 1'b1);

        // "hello" in PS/2 scancode set 2. Nothing is forced: these are real
        // 11-bit frames clocked in at PS2_CLK/PS2_DAT.
        ps2_key(8'h33);   // h
        ps2_key(8'h24);   // e
        ps2_key(8'h4B);   // l
        ps2_key(8'h4B);   // l
        ps2_key(8'h44);   // o

        // After the fifth key the boot sector falls out of its loop and halts
        // for good.
        i = 0;
        // Long enough for the kernel to finish echoing AND to run the
        // graphics block after it. Clearing the 64,000-byte aperture is
        // 32,000 word writes -- around 320,000 CPU clocks, which is nothing
        // on hardware and dominates this wait.
        while (i < 5000000) begin @(negedge CLOCK_50); i++; end
        chk("machine reached the boot sector's HLT", dut.halted, 1'b1);
        chk("halt is visible on LEDR[7]", LEDR[7], 1'b1);
        chk("no unexpected trap was taken", dut.dbg_int_taken, 1'b0);

        $display("");
        for (r = 0; r <= 6; r++) begin
            got = read_line(r, want[r].len());
            $display("  line %0d: \"%s\"", r, got);
            checks++;
            if (got != want[r]) begin
                $display("FAIL line %0d mismatch", r);
                $display("    expected: \"%s\"", want[r]);
                errors++;
            end
        end
        $display("");

        // ---- the BIOS data area was set up ----
        // The BDA lives at segment 0040, so 40:10 is physical 0410. chip.mem is
        // word-addressed, and 40:13 is an ODD offset, so the memory-size word
        // straddles two of those words.
        chk("equipment word",  chip.mem['h410 >> 1], 16'h0021);
        chk("memory size, KB",
            {chip.mem['h414 >> 1][7:0], chip.mem['h413 >> 1][15:8]}, 16'd640);

        // ---- the interrupt vector table points into the BIOS ----
        chk("INT 10h vector segment", chip.mem[('h10*4 + 2) >> 1], 16'hF000);
        chk("INT 13h vector segment", chip.mem[('h13*4 + 2) >> 1], 16'hF000);
        chk("INT 16h vector segment", chip.mem[('h16*4 + 2) >> 1], 16'hF000);
        // An unused vector must still be filled, or a stray interrupt would
        // run whatever happened to be in RAM.
        chk("unused vector filled",   chip.mem[('h40*4 + 2) >> 1], 16'hF000);

        // ---- the boot sector really was loaded where a boot sector goes ----
        chk("boot signature at 0000:7DFE", chip.mem['h7DFE >> 1], 16'hAA55);
        checks++;
        if (chip.mem['h7C00 >> 1] === 16'h0000) begin
            $display("FAIL nothing was loaded at 0000:7C00");
            errors++;
        end

        // ---- the cursor followed the text ----
        // Four lines were printed, so the CRTC cursor must sit on row 4.
        chk("cursor tracked the text", dut.u_crtc.cursor_addr, 11'd485);
        chk("cursor still enabled", dut.u_crtc.cursor_en, 1'b1);

        // ---- the font image really loaded ----
        glyph_bits = 0;
        for (i = 0; i < 16; i++)
            glyph_bits += $countones(dut.u_vga.u_font.g_inferred.rom[{8'h41, i[3:0]}]);
        checks++;
        if (glyph_bits == 0) begin
            $display("FAIL font ROM is empty -- the image did not load");
            errors++;
        end

        // INT 13h AH=08, as the kernel left it at 0000:0600. Reporting the
        // last cylinder rather than the count is the part that is easy to get
        // wrong, and a BIOS that claims one cylinder describes a disk one
        // track long.
        chk("INT 13h AH=08 last cylinder and sectors per track",
            chip.mem['h600 >> 1], {8'((GEO_BIOS_CYLS - 1)), 8'(GEO_SPT)});
        chk("INT 13h AH=08 last head and drive count",
            chip.mem['h602 >> 1], {8'((GEO_HEADS - 1)), 8'd1});

        // ---- graphics mode, set and drawn by the loaded kernel ----
        // Read straight out of the framebuffer and the palette the video
        // controller scans, so this covers INT 10h mode 13h, the A0000
        // decode, the byte lanes and the 3C8/3C9 DAC in one go.
        chk("mode register selected graphics", dut.mode_gfx, 1'b1);
        // ...and the BIOS's read-back of port 3D8 must agree with it. The BDA
        // mode byte is only the BIOS's opinion; this is the hardware's.
        chk("BIOS read the mode register back as graphics",
            chip.mem['h480 >> 1][7:0], 8'h02);
        chk("kernel plotted pixel (0,0)",   dut.u_mem.u_fb.ram_lo[0], 8'h01);
        chk("kernel plotted pixel (1,0)",   dut.u_mem.u_fb.ram_hi[0], 8'h02);
        // 199*320 + 319 = 63999, an odd offset, so it lands in the high lane
        // of word 31999 -- which is what makes it a byte-lane check too.
        chk("kernel plotted the last pixel", dut.u_mem.u_fb.ram_hi[31999], 8'h03);
        // Bar 3 covers x=48..63 of every row, so row 1 pixel 50 must be the
        // bar index -- which also proves the row-replicating REP MOVSW ran.
        chk("colour bars replicated down the screen",
            dut.u_mem.u_fb.ram_lo[(320 + 50) >> 1], 8'd3);
        // ---- the blitter, driven by the loaded kernel ----
        // Read straight out of the framebuffer the video controller scans, so
        // this covers the 0330 port decode, the register file, the shared
        // framebuffer port and the byte lanes from software down.
        chk("blitter filled the first pixel of its rectangle",
            dut.u_mem.u_fb.ram_hi[(100*320 + 1) >> 1], 8'h2A);
        chk("blitter filled the last pixel of the last row",
            dut.u_mem.u_fb.ram_lo[(100*320 + 1 + 7*320 + 15) >> 1], 8'h2A);
        chk("blitter left the pixel before the rectangle alone",
            dut.u_mem.u_fb.ram_lo[(100*320) >> 1], 8'd0);
        // The kernel's own verdict, which is what the hardware check reads
        // back over JTAG since the framebuffer is on-chip and invisible to it.
        chk("the kernel's own blitter self-check passed",
            chip.mem['h604 >> 1][7:0], 8'hA0);   // 604 is even: low lane

        chk("blitter copied the rectangle elsewhere",
            dut.u_mem.u_fb.ram_lo[(120*320 + 2) >> 1], 8'h2A);
        chk("the copy's last row arrived too",
            dut.u_mem.u_fb.ram_hi[(120*320 + 2 + 7*320 + 15) >> 1], 8'h2A);

        chk("palette entry 1 loaded through 3C8/3C9",
            dut.u_dac.pal[1], 18'({6'd63, 6'd0, 6'd0}));

        chk("no SDRAM protocol errors", chip.errors, 0);

        $display("");
        $display("  %0d cycles, %0d with a bus request (%0.1f%%)",
                 cyc_total, bus_cycles, 100.0 * bus_cycles / cyc_total);
        $display("  stalled waiting on SDRAM:     %0d (%0.1f%%)",
                 stall_ram, 100.0 * stall_ram / cyc_total);
        $display("  stalled waiting on ROM/other: %0d (%0.1f%%)",
                 stall_other, 100.0 * stall_other / cyc_total);
        $display("");
        $display("==================================");
        $display(" checks: %0d   failures: %0d", checks, errors);
        $display("==================================");
        if (errors == 0) $display("ALL TESTS PASSED");
        $finish;
    end

    initial begin
        #400000000;
        $display("FAIL global timeout (IP=%04h halted=%b)", dut.dbg_ip, dut.halted);
        $display(" checks: %0d   failures: %0d", checks, errors + 1);
        $finish;
    end

endmodule
