`timescale 1ns/1ns
//
// Block storage device.
//
// The image under test is the one tools/gen_disk.py produces, and it is
// structured so that a wrong answer is recognisably wrong rather than merely
// different: every sector carries its own number and a per-word value derived
// from it. Reading the wrong sector, re-reading a stale one, or slipping the
// word index by one each produce a distinct failure.
//
// The register interface is driven the way io_decode drives it: `sel` and
// `reg_sel` are levels held for the whole bus cycle, `rd`/`wr` are
// single-cycle strobes marking the completed access. Getting that wrong is
// exactly the defect tb_iodecode exists to catch, so it is not re-litigated
// here -- this testbench assumes the contract and checks the device.
//
module tb_storage;

    localparam int SECTORS = 64;

    logic        clk = 0, rst_n = 0;
    logic        sel = 0, rd = 0, wr = 0;
    logic [2:0]  reg_sel = 3'd0;
    logic [15:0] wdata = 16'h0000, rdata;

    // The ROM backend. Its SDRAM port is present but never asks for anything,
    // so it is tied off here; sim/tb_storage_sdram.sv covers the other backend.
    logic [23:0] mem_addr;
    logic [15:0] mem_wdata, mem_rdata = 16'h0000;
    logic [1:0]  mem_be;
    logic        mem_rd, mem_wr, mem_ready = 1'b0;

    storage #(.SECTORS(SECTORS), .USE_SDRAM(1'b0)) dut (
        .clk (clk), .rst_n (rst_n),
        .sel (sel), .reg_sel (reg_sel), .rd (rd), .wr (wr),
        .wdata (wdata), .rdata (rdata),
        .mem_addr (mem_addr), .mem_wdata (mem_wdata), .mem_be (mem_be),
        .mem_rd (mem_rd), .mem_wr (mem_wr),
        .mem_rdata (mem_rdata), .mem_ready (mem_ready)
    );

    // The ROM backend must never touch the memory bus.
    int stray_mem = 0;
    always @(posedge clk) if (rst_n && (mem_rd || mem_wr)) stray_mem++;

    always #5 clk = ~clk;

    localparam logic [2:0] R_DATA    = 3'd0;
    localparam logic [2:0] R_LBA_LO  = 3'd1;
    localparam logic [2:0] R_LBA_HI  = 3'd2;
    localparam logic [2:0] R_CMD     = 3'd3;
    localparam logic [2:0] R_SECTORS = 3'd4;

    // Generated by tools/gen_disk.py from rom/geometry.py, so the expected
    // geometry here cannot drift from the image or from the BIOS.
    `include "geometry.svh"

    int errors = 0, checks = 0;
    task chk(input string nm, input int got, input int exp);
        checks++;
        if (got !== exp) begin
            $display("FAIL %-46s got=%04h exp=%04h", nm, got, exp);
            errors++;
        end
    endtask

    task reg_write(input [2:0] r, input [15:0] v);
        begin
            @(negedge clk); sel = 1; reg_sel = r; wdata = v;
            @(negedge clk); wr = 1;
            @(negedge clk); wr = 0; sel = 0;
            @(negedge clk);
        end
    endtask

    task reg_read(input [2:0] r, output [15:0] v);
        begin
            @(negedge clk); sel = 1; reg_sel = r;
            @(negedge clk); rd = 1;
            v = rdata;                       // captured in the strobe cycle
            @(negedge clk); rd = 0; sel = 0;
            @(negedge clk);
        end
    endtask

    // Issue a read and wait out BUSY, counting the polls that actually saw it
    // asserted -- if that count is zero the latency is not being modelled and
    // a real device would break the same software.
    int busy_polls;
    task start_read(input [23:0] lba);
        logic [15:0] st;
        begin
            reg_write(R_LBA_LO, lba[15:0]);
            reg_write(R_LBA_HI, {8'h00, lba[23:16]});
            reg_write(R_CMD,    16'h0001);
            busy_polls = 0;
            reg_read(R_CMD, st);
            while (st[0]) begin              // BUSY
                busy_polls++;
                reg_read(R_CMD, st);
            end
        end
    endtask

    logic [15:0] v, st;
    int i, e;
    bit found;
    string dirname, fstype;
    logic [15:0] sec [0:255];

    // Byte n of the sector just read. The device is word-addressed, so an odd
    // byte is the high half of its word.
    function automatic [7:0] bval(input int n);
        bval = n[0] ? sec[n >> 1][15:8] : sec[n >> 1][7:0];
    endfunction

    initial begin
        repeat (4) @(negedge clk);
        rst_n = 1;
        @(negedge clk);

        // ---- geometry ----
        reg_read(R_SECTORS, v);
        chk("device reports its size", v, SECTORS);

        reg_read(R_CMD, st);
        chk("idle: not busy", st[0], 1'b0);
        chk("idle: no data offered", st[1], 1'b0);
        chk("idle: no error", st[2], 1'b0);

        // ---- sector 0 is a FAT12 boot sector ----
        start_read(24'd0);
        chk("BUSY was actually observed", (busy_polls > 0), 1'b1);

        reg_read(R_CMD, st);
        chk("after BUSY: data is offered", st[1], 1'b1);
        chk("after BUSY: no error", st[2], 1'b0);

        // Pull the whole sector in first. BPB fields sit at odd byte offsets,
        // so checking them against a 16-bit port means indexing by byte
        // rather than counting words and hoping.
        for (i = 0; i < 256; i++) reg_read(R_DATA, sec[i]);

        reg_read(R_CMD, st);
        chk("data no longer offered after 256 words", st[1], 1'b0);

        // A FAT volume always opens with a short jump over the BPB; without
        // it the CPU would execute the parameter block as code.
        chk("boot sector opens with a jump", bval(0), 8'hEB);
        chk("jump lands on the code at 3Eh", bval(1), 8'h3C);

        chk("BPB bytes per sector", {bval(12), bval(11)}, 16'd512);
        chk("BPB sectors per cluster", bval(13), 8'd1);
        chk("BPB reserved sectors", {bval(15), bval(14)}, 16'd1);
        chk("BPB number of FATs", bval(16), 8'd2);
        chk("BPB root entries", {bval(18), bval(17)}, 16'd112);
        chk("BPB total sectors", {bval(20), bval(19)}, 16'd256);
        chk("BPB media descriptor", bval(21), 8'hF8);
        // Geometry has to match what the BIOS's INT 13h does, or every read
        // the boot sector issues lands on the wrong sector. Both sides now take
        // it from rom/geometry.py, so these track whatever image was last
        // uploaded rather than a constant of their own.
        chk("BPB sectors per track", {bval(25), bval(24)}, GEO_SPT);
        chk("BPB heads", {bval(27), bval(26)}, GEO_HEADS);
        chk("extended boot signature", bval(38), 8'h29);

        fstype = "";
        for (i = 54; i < 62; i++) fstype = {fstype, string'(bval(i))};
        checks++;
        if (fstype != "FAT12   ") begin
            $display("FAIL filesystem type is \"%s\", expected \"FAT12   \"", fstype);
            errors++;
        end

        chk("boot signature at the end of the sector",
            {bval(511), bval(510)}, 16'hAA55);

        // ---- sector 1 is the first FAT ----
        start_read(24'd1);
        reg_read(R_DATA, v);
        chk("FAT[0] carries the media descriptor", v, 16'hFFF8);
        reg_read(R_DATA, v);
        chk("FAT[1] is the end-of-chain marker", v[7:0], 8'hFF);

        // ---- the root directory ----
        // reserved(1) + 2 FATs x 1 sector = 3. KERNEL.BIN is no longer the
        // first entry -- padding is deliberately placed ahead of it so that
        // loading it crosses a head boundary -- so this searches the directory
        // the way the boot sector does rather than matching entry 0.
        start_read(24'd3);
        found = 0;
        for (e = 0; e < 8; e++) begin
            dirname = "";
            for (i = 0; i < 6; i++) begin
                reg_read(R_DATA, v);
                dirname = {dirname, string'(v[7:0]), string'(v[15:8])};
            end
            for (i = 6; i < 16; i++) reg_read(R_DATA, v);   // rest of the entry
            $display("  root directory entry %0d: \"%s\"", e, dirname);
            if (dirname == "KERNEL  BIN ") found = 1;
        end
        $display("");
        checks++;
        if (!found) begin
            $display("FAIL KERNEL.BIN is not in the root directory");
            errors++;
        end

        // ---- the last sector is reachable ----
        start_read(SECTORS - 1);
        reg_read(R_CMD, st);
        chk("last sector read without error", st[2], 1'b0);

        // ---- re-reading restarts at word 0 ----
        start_read(24'd1);
        reg_read(R_DATA, v);
        chk("re-read restarts at word 0", v, 16'hFFF8);

        // ---- out of range is refused, not wrapped ----
        start_read(SECTORS);          // one past the end
        reg_read(R_CMD, st);
        chk("out-of-range read sets ERR", st[2], 1'b1);
        chk("out-of-range read offers no data", st[1], 1'b0);

        start_read(24'hFFFFFF);
        reg_read(R_CMD, st);
        chk("far out-of-range read sets ERR", st[2], 1'b1);

        // ---- the device recovers: a valid read clears the error ----
        start_read(24'd1);
        reg_read(R_CMD, st);
        chk("valid read clears ERR", st[2], 1'b0);
        chk("valid read offers data again", st[1], 1'b1);
        reg_read(R_DATA, v); chk("recovered read returns the FAT", v, 16'hFFF8);

        // ---- writes are refused: the backing store is ROM ----
        reg_write(R_LBA_LO, 16'd2);
        reg_write(R_LBA_HI, 16'd0);
        reg_write(R_CMD,    16'h0002);       // WRITE
        reg_read(R_CMD, st);
        chk("write command sets ERR", st[2], 1'b1);
        chk("write command offers no data", st[1], 1'b0);

        // ---- an unknown command is refused too ----
        reg_write(R_CMD, 16'h00FF);
        reg_read(R_CMD, st);
        chk("unknown command sets ERR", st[2], 1'b1);

        chk("the ROM backend never used the memory bus", stray_mem, 0);

        $display("");
        $display("==================================");
        $display(" checks: %0d   failures: %0d", checks, errors);
        $display("==================================");
        if (errors == 0) $display("ALL TESTS PASSED");
        $finish;
    end

    initial begin
        #5000000;
        $display("FAIL global timeout");
        $display(" checks: %0d   failures: %0d", checks, errors + 1);
        $finish;
    end

endmodule
