#!/usr/bin/env python3
"""
Generate DE1-SoC pin assignments for FPGA80186 from the Terasic User Manual.

Pin locations are board facts. Typing eighty of them by hand invites a
transposed character that produces a bitstream which does nothing, or which
drives a pin the board already drives. So they are extracted from the manual's
own tables instead, and the script fails loudly if any top-level port does not
get a pin, or if the manual yields two different pins for one signal.

Usage:
    pdftotext -layout DE1-SoC_User_manual.pdf de1.txt
    python3 tools/gen_pins.py de1.txt modules/FPGA80186.sv > pins.qsf
"""
import re
import sys
import collections


def load_pins(path):
    """Signal name -> pin, from lines shaped 'NAME   PIN_XXX   description'."""
    txt = open(path, encoding="utf-8", errors="replace").read()
    pat = re.compile(r'^\s*([A-Z][A-Z0-9_]*(?:\[\d+\])?)\s+(PIN_[A-Z0-9]+)\b', re.M)
    found = collections.defaultdict(set)
    for name, pin in pat.findall(txt):
        found[name].add(pin)

    conflicts = {k: sorted(v) for k, v in found.items() if len(v) > 1}
    if conflicts:
        for k, v in conflicts.items():
            print(f"CONFLICT: {k} appears as {v}", file=sys.stderr)
        sys.exit("manual yielded conflicting pins; refusing to emit anything")

    return {k: v.pop() for k, v in found.items()}


def load_ports(path):
    """Top-level ports, expanded to one entry per bit for vectors."""
    txt = open(path, encoding="utf-8").read()
    body = txt[txt.index("module FPGA80186"):]
    body = body[:body.index(");")]

    ports = []
    for line in body.splitlines():
        line = line.split("//")[0]
        m = re.search(r'\b(?:input|output|inout)\s+(?:logic|wire)?\s*'
                      r'(?:\[\s*(\d+)\s*:\s*(\d+)\s*\])?\s*([A-Za-z_]\w*)', line)
        if not m:
            continue
        hi, lo, name = m.group(1), m.group(2), m.group(3)
        if hi is None:
            ports.append(name)
        else:
            for i in range(int(lo), int(hi) + 1):
                ports.append(f"{name}[{i}]")
    return ports


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    pins = load_pins(sys.argv[1])
    ports = load_ports(sys.argv[2])

    missing = [p for p in ports if p not in pins]
    if missing:
        for p in missing:
            print(f"NO PIN FOR: {p}", file=sys.stderr)
        sys.exit("some top-level ports have no pin; refusing to emit a partial map")

    # Two ports on one pin would be a short between outputs. Check the mapping
    # in reverse as well, not just that every port found something.
    used = collections.defaultdict(list)
    for p in ports:
        used[pins[p]].append(p)
    dupes = {k: v for k, v in used.items() if len(v) > 1}
    if dupes:
        for pin, names in dupes.items():
            print(f"PIN REUSED: {pin} <- {names}", file=sys.stderr)
        sys.exit("two top-level ports resolved to the same pin")

    print("# DE1-SoC pin assignments, generated by tools/gen_pins.py from the")
    print("# Terasic DE1-SoC User Manual. Do not edit by hand -- regenerate.")
    print(f"# {len(ports)} ports assigned.")
    print()
    for p in ports:
        print(f"set_location_assignment {pins[p]} -to {p}")
        print(f'set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to {p}')


if __name__ == "__main__":
    main()
