#!/usr/bin/env python3
"""
Convert a $readmemh image into a .mif.

    python3 tools/hex2mif.py rom/bios.lo.hex rom/bios.lo.mif 8

The RTL loads its memories with $readmemh, which is portable and simulates
without vendor libraries. An `altera_syncram` instantiated for the In-System
Memory Content Editor wants a .mif instead, so the same contents have to exist
in both forms -- this writes the second from the first rather than having two
generators that could drift apart.

WIDTH must match the memory. A .mif whose width or depth disagrees with the
memory it initialises is rejected by Quartus rather than silently padded, which
is the desired behaviour but means the number has to be right: 8 for the BIOS
byte banks and the font, 16 for the disk.
"""
import os
import sys


def read_hex(path):
    """One value per line, ignoring // comments and blank lines."""
    vals = []
    for line in open(path):
        line = line.split("//")[0].strip()
        if not line:
            continue
        for tok in line.split():
            vals.append(int(tok, 16))
    return vals


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__.strip())

    src = sys.argv[1]
    out = sys.argv[2]
    width = int(sys.argv[3]) if len(sys.argv) > 3 else 8

    if not os.path.exists(src):
        sys.exit("error: %s does not exist" % src)

    vals = read_hex(src)
    if not vals:
        sys.exit("error: %s holds no data" % src)

    mask = (1 << width) - 1
    digits = (width + 3) // 4
    over = [v for v in vals if v > mask]
    if over:
        sys.exit("error: %d values in %s exceed %d bits"
                 % (len(over), src, width))

    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w") as f:
        f.write("-- Generated by tools/hex2mif.py from %s\n"
                % os.path.basename(src))
        f.write("-- Keep this in step with the .hex: the RTL simulates from\n")
        f.write("-- one and synthesises from the other.\n")
        f.write("DEPTH = %d;\n" % len(vals))
        f.write("WIDTH = %d;\n" % width)
        f.write("ADDRESS_RADIX = HEX;\n")
        f.write("DATA_RADIX = HEX;\n")
        f.write("CONTENT BEGIN\n")
        for i, v in enumerate(vals):
            f.write("  %X : %0*X;\n" % (i, digits, v))
        f.write("END;\n")

    print("wrote %s: DEPTH=%d WIDTH=%d" % (out, len(vals), width))


if __name__ == "__main__":
    main()
