#!/usr/bin/env python3
"""
Convert a disk image into a .mif for the In-System Memory Content Editor.

    python3 tools/img2mif.py yourdisk.img rom/disk.mif

WHAT THIS IS FOR. The In-System Memory Content Editor rewrites the contents of
an ON-CHIP memory in an already-programmed FPGA, over the same USB-Blaster
cable used to load the bitstream. That means a new disk image without
re-running synthesis -- minutes instead of a full rebuild.

It does NOT take or produce a .sof. The .sof is the bitstream, programmed
first; ISMCE then pushes memory contents into the running device. The file it
imports is a .mif, which is what this writes.

THE SIZE CEILING STILL APPLIES, and it is the reason this is not a route to
running a real DOS floppy. ISMCE only reaches on-chip memory, so the image must
fit in block RAM -- about 736 sectors (368 KB) with the rest of this design in
place. A 1.44 MB floppy is roughly four times that. For anything larger the
image has to live in SDRAM, which ISMCE cannot touch; that needs the JTAG
loader instead.

USING IT, once the disk memory has been built with ISMCE enabled:

    quartus_pgm -m jtag -o "p;output_files/FPGA80186.sof@2"
    quartus_stp -t tools/ismce_load.tcl rom/disk.mif

WIDTH. storage.sv holds the disk as 16-bit words, so the .mif is written 16
bits wide with one word per address -- the same organisation $readmemh gives
it from rom/disk.hex. A .mif whose width or depth disagrees with the memory is
rejected by the editor rather than silently truncated.
"""
import os
import sys

SECTOR = 512


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__.strip())

    src = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else "rom/disk.mif"

    if not os.path.exists(src):
        sys.exit("error: %s does not exist" % src)

    data = open(src, "rb").read()
    if len(data) % 2:
        data += b"\0"

    words = len(data) // 2
    sectors = (len(data) + SECTOR - 1) // SECTOR

    print("read %s: %d bytes, %d sectors" % (src, len(data), sectors))
    if sectors > 736:
        print("  WARNING: %d sectors will not fit in on-chip memory." % sectors)
        print("           The ceiling is around 736 sectors (368 KB), so the")
        print("           In-System Memory Content Editor cannot load this.")
        print("           An image this size has to go in SDRAM.")

    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w") as f:
        f.write("-- Generated by tools/img2mif.py from %s\n"
                % os.path.basename(src))
        f.write("-- For the In-System Memory Content Editor; 16-bit words, as\n")
        f.write("-- storage.sv holds them.\n")
        f.write("DEPTH = %d;\n" % words)
        f.write("WIDTH = 16;\n")
        f.write("ADDRESS_RADIX = HEX;\n")
        f.write("DATA_RADIX = HEX;\n")
        f.write("CONTENT BEGIN\n")
        for i in range(words):
            w = data[i * 2] | (data[i * 2 + 1] << 8)
            f.write("  %X : %04X;\n" % (i, w))
        f.write("END;\n")

    print("wrote %s: DEPTH=%d WIDTH=16" % (out, words))


if __name__ == "__main__":
    main()
